### Add place
POST http://localhost:8080/place/insert/train/1
Content-Type: application/json

{
  "number": 1,
  "placeClass": "ClassA"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train/1
Content-Type: application/json

{
  "number": 2,
  "placeClass": "ClassA"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train/1
Content-Type: application/json

{
  "number": 3,
  "placeClass": "ClassB"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train/1
Content-Type: application/json

{
  "number": 4,
  "placeClass": "ClassB"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train/1
Content-Type: application/json

{
  "number": 5,
  "placeClass": "ClassB"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train/1
Content-Type: application/json

{
  "number": 6,
  "placeClass": "ClassB"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train-express/2
Content-Type: application/json

{
  "number": 1,
  "placeClass": "ClassA"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train-express/2
Content-Type: application/json

{
  "number": 2,
  "placeClass": "ClassA"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train-express/2
Content-Type: application/json

{
  "number": 3,
  "placeClass": "ClassB"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place
POST http://localhost:8080/place/insert/train-express/2
Content-Type: application/json

{
  "number": 4,
  "placeClass": "ClassB"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


