### Add passenger
POST http://localhost:8080/passenger/insert/place/1
Content-Type: application/json

{
  "firstName": "1",
  "secondName": "1",
  "gender": "Male"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add passenger
POST http://localhost:8080/passenger/insert/place/2
Content-Type: application/json

{
  "firstName": "2",
  "secondName": "2",
  "gender": "Female"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add passenger
POST http://localhost:8080/passenger/insert/place/3
Content-Type: application/json

{
  "firstName": "3",
  "secondName": "3",
  "gender": "Male"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add passenger
POST http://localhost:8080/passenger/insert/place/4
Content-Type: application/json

{
  "firstName": "4",
  "secondName": "4",
  "gender": "Male"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add passenger
POST http://localhost:8080/passenger/
Content-Type: application/json

{
  "firstName": "5",
  "secondName": "5",
  "gender": "Male"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place for passenger
POST http://localhost:8080/passenger/5/place/5

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add place for passenger
POST http://localhost:8080/passenger/5/place/6

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add passenger
POST http://localhost:8080/passenger/insert/place/7
Content-Type: application/json

{
  "firstName": "6",
  "secondName": "6",
  "gender": "Male"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Add passenger
POST http://localhost:8080/passenger/insert/place/8
Content-Type: application/json

{
  "firstName": "7",
  "secondName": "7",
  "gender": "Female"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

